<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32166" started-at="2016-11-18T04:05:22Z" finished-at="2016-11-18T04:05:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32166" started-at="2016-11-18T04:05:22Z" finished-at="2016-11-18T04:05:54Z">
      <class name="testcases.TC_001">
        <test-method status="PASS" signature="bMet()[pri:0, instance:testcases.TC_001@4678c730]" name="bMet" is-config="true" duration-ms="22066" started-at="2016-11-18T09:35:22Z" finished-at="2016-11-18T09:35:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bMet -->
        <test-method status="FAIL" signature="tCase1()[pri:0, instance:testcases.TC_001@4678c730]" name="tCase1" duration-ms="4757" started-at="2016-11-18T09:35:44Z" finished-at="2016-11-18T09:35:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[ERROR - URL Not Matching] http://www.facebook.com expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [ERROR - URL Not Matching] http://www.facebook.com expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at pages.Login.enterUserName(Login.java:27)
	at testcases.TC_001.tCase1(TC_001.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tCase1 -->
        <test-method status="PASS" signature="aMet()[pri:0, instance:testcases.TC_001@4678c730]" name="aMet" is-config="true" duration-ms="5125" started-at="2016-11-18T09:35:49Z" finished-at="2016-11-18T09:35:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aMet -->
      </class> <!-- testcases.TC_001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
